charpool.o: charpool.cc nbase/nbase.h nbase/nbase_config.h nbase/getopt.h \
  nbase/nbase_ipv6.h charpool.h nmap_error.h nmap_config.h nbase/nbase.h
FingerPrintResults.o: FingerPrintResults.cc FingerPrintResults.h nmap.h \
  nmap_config.h nbase/nbase.h nbase/nbase_config.h nbase/getopt.h \
  nbase/nbase_ipv6.h global_structures.h FPEngine.h nsock/include/nsock.h \
  nsock/include/nsock_config.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h osscan.h Target.h libnetutil/netutil.h \
  nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lua.h \
  liblua/lualib.h portreasons.h portlist.h tcpip.h \
  libdnet-stripped/include/dnet.h scan_engine.h NmapOps.h output.h \
  nsock/include/nsock.h
FPEngine.o: FPEngine.cc FPEngine.h nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h Target.h FingerPrintResults.h \
  libnetutil/netutil.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lua.h liblua/lualib.h portreasons.h portlist.h \
  tcpip.h libdnet-stripped/include/dnet.h scan_engine.h NmapOps.h \
  output.h nsock/include/nsock.h nmap_error.h osscan.h liblinear/linear.h
FPModel.o: FPModel.cc FingerPrintResults.h nmap.h nmap_config.h \
  nbase/nbase.h nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h FPEngine.h nsock/include/nsock.h \
  nsock/include/nsock_config.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h liblinear/linear.h
idle_scan.o: idle_scan.cc idle_scan.h nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h timing.h osscan2.h Target.h FingerPrintResults.h \
  FPEngine.h nsock/include/nsock.h nsock/include/nsock_config.h \
  libnetutil/npacket.h libnetutil/ApplicationLayerElement.h \
  libnetutil/PacketElement.h libnetutil/netutil.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lua.h liblua/lualib.h \
  portreasons.h portlist.h tcpip.h libdnet-stripped/include/dnet.h \
  scan_engine.h NmapOps.h output.h nsock/include/nsock.h services.h \
  utils.h nmap_error.h struct_ip.h
MACLookup.o: MACLookup.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h MACLookup.h nbase/nbase.h NmapOps.h output.h \
  portlist.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lua.h liblua/lualib.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap_error.h charpool.h
main.o: main.cc nmap.h nmap_config.h nbase/nbase.h nbase/nbase_config.h \
  nbase/getopt.h nbase/nbase_ipv6.h global_structures.h NmapOps.h \
  output.h portlist.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lua.h liblua/lualib.h portreasons.h \
  nsock/include/nsock.h nsock/include/nsock_config.h utils.h nmap_error.h
nmap.o: nmap.cc nmap.h nmap_config.h nbase/nbase.h nbase/nbase_config.h \
  nbase/getopt.h nbase/nbase_ipv6.h global_structures.h osscan.h \
  FingerPrintResults.h FPEngine.h nsock/include/nsock.h \
  nsock/include/nsock_config.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h Target.h libnetutil/netutil.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lua.h \
  liblua/lualib.h portreasons.h portlist.h tcpip.h \
  libdnet-stripped/include/dnet.h scan_engine.h osscan2.h idle_scan.h \
  timing.h NmapOps.h output.h nsock/include/nsock.h MACLookup.h \
  nbase/nbase.h traceroute.h nmap_tty.h nmap_dns.h nmap_ftp.h services.h \
  protocols.h targets.h TargetGroup.h service_scan.h libpcre/pcre.h \
  charpool.h nmap_error.h utils.h xml.h libdnet-stripped/include/config.h
nmap_dns.o: nmap_dns.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h NmapOps.h output.h portlist.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lua.h \
  liblua/lualib.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap_dns.h utils.h nmap_error.h nmap_tty.h \
  timing.h Target.h FingerPrintResults.h FPEngine.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h tcpip.h \
  libdnet-stripped/include/dnet.h scan_engine.h
nmap_error.o: nmap_error.cc nmap_error.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h output.h \
  portlist.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lua.h liblua/lualib.h nmap.h global_structures.h portreasons.h \
  nsock/include/nsock.h nsock/include/nsock_config.h NmapOps.h xml.h
nmap_ftp.o: nmap_ftp.cc nmap_ftp.h nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h output.h portlist.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lua.h liblua/lualib.h \
  portreasons.h nsock/include/nsock.h nsock/include/nsock_config.h \
  NmapOps.h nmap_error.h tcpip.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h Target.h FingerPrintResults.h \
  FPEngine.h libnetutil/npacket.h libnetutil/ApplicationLayerElement.h \
  libnetutil/PacketElement.h libnetutil/netutil.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h scan_engine.h
NmapOps.o: NmapOps.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h NmapOps.h output.h portlist.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lua.h \
  liblua/lualib.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h services.h utils.h nmap_error.h
NmapOutputTable.o: NmapOutputTable.cc NmapOutputTable.h nmap.h \
  nmap_config.h nbase/nbase.h nbase/nbase_config.h nbase/getopt.h \
  nbase/nbase_ipv6.h global_structures.h utils.h nmap_error.h
nmap_tty.o: nmap_tty.cc nmap_config.h nmap.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h nmap_tty.h utils.h nmap_error.h NmapOps.h output.h \
  portlist.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lua.h liblua/lualib.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h
osscan2.o: osscan2.cc osscan.h nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h FingerPrintResults.h FPEngine.h \
  nsock/include/nsock.h nsock/include/nsock_config.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h Target.h libnetutil/netutil.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lua.h \
  liblua/lualib.h portreasons.h portlist.h tcpip.h \
  libdnet-stripped/include/dnet.h scan_engine.h osscan2.h timing.h \
  NmapOps.h output.h nsock/include/nsock.h utils.h nmap_error.h \
  struct_ip.h
osscan.o: osscan.cc osscan.h nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h FingerPrintResults.h FPEngine.h \
  nsock/include/nsock.h nsock/include/nsock_config.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h Target.h libnetutil/netutil.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lua.h \
  liblua/lualib.h portreasons.h portlist.h tcpip.h \
  libdnet-stripped/include/dnet.h scan_engine.h timing.h NmapOps.h \
  output.h nsock/include/nsock.h nmap_tty.h charpool.h nmap_error.h \
  utils.h
output.o: output.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h output.h portlist.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lua.h liblua/lualib.h \
  portreasons.h nsock/include/nsock.h nsock/include/nsock_config.h \
  osscan.h FingerPrintResults.h FPEngine.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h Target.h libnetutil/netutil.h tcpip.h \
  libdnet-stripped/include/dnet.h scan_engine.h NmapOps.h \
  NmapOutputTable.h MACLookup.h nbase/nbase.h protocols.h utils.h \
  nmap_error.h xml.h
payload.o: payload.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h NmapOps.h output.h portlist.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lua.h \
  liblua/lualib.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h payload.h utils.h nmap_error.h
portlist.o: portlist.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h portlist.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lua.h liblua/lualib.h portreasons.h \
  nmap_error.h NmapOps.h output.h nsock/include/nsock.h \
  nsock/include/nsock_config.h services.h protocols.h tcpip.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/netutil.h
portreasons.o: portreasons.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h portlist.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lua.h liblua/lualib.h portreasons.h NmapOps.h \
  output.h nsock/include/nsock.h nsock/include/nsock_config.h Target.h \
  FingerPrintResults.h FPEngine.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h tcpip.h \
  libdnet-stripped/include/dnet.h scan_engine.h xml.h
protocols.o: protocols.cc protocols.h nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h NmapOps.h output.h portlist.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lua.h \
  liblua/lualib.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h services.h charpool.h nmap_error.h utils.h
scan_engine.o: scan_engine.cc portreasons.h nmap.h nmap_config.h \
  nbase/nbase.h nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h scan_engine.h timing.h NmapOps.h \
  output.h portlist.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lua.h liblua/lualib.h nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap_tty.h payload.h Target.h \
  FingerPrintResults.h FPEngine.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h tcpip.h targets.h \
  TargetGroup.h utils.h nmap_error.h struct_ip.h
service_scan.o: service_scan.cc service_scan.h nmap.h nmap_config.h \
  nbase/nbase.h nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h portlist.h nse_main.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lua.h liblua/lualib.h portreasons.h \
  libpcre/pcre.h timing.h NmapOps.h output.h nsock/include/nsock.h \
  nsock/include/nsock_config.h Target.h FingerPrintResults.h FPEngine.h \
  libnetutil/npacket.h libnetutil/ApplicationLayerElement.h \
  libnetutil/PacketElement.h libnetutil/netutil.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h tcpip.h \
  libdnet-stripped/include/dnet.h scan_engine.h utils.h nmap_error.h \
  protocols.h nmap_tty.h
services.o: services.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h services.h NmapOps.h output.h portlist.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lua.h \
  liblua/lualib.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h charpool.h nmap_error.h utils.h
Target.o: Target.cc Target.h nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h FingerPrintResults.h FPEngine.h \
  nsock/include/nsock.h nsock/include/nsock_config.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lua.h liblua/lualib.h \
  portreasons.h portlist.h tcpip.h libdnet-stripped/include/dnet.h \
  scan_engine.h NmapOps.h output.h nsock/include/nsock.h utils.h \
  nmap_error.h
TargetGroup.o: TargetGroup.cc tcpip.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h nmap.h nbase/nbase.h \
  global_structures.h TargetGroup.h NmapOps.h output.h portlist.h \
  nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lua.h \
  liblua/lualib.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap_error.h libnetutil/netutil.h
targets.o: targets.cc nbase/nbase_addrset.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_config.h \
  nbase/nbase_ipv6.h targets.h nmap_config.h nmap.h nbase/nbase.h \
  global_structures.h TargetGroup.h timing.h NmapOps.h output.h \
  portlist.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lua.h liblua/lualib.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h Target.h FingerPrintResults.h FPEngine.h \
  libnetutil/npacket.h libnetutil/ApplicationLayerElement.h \
  libnetutil/PacketElement.h libnetutil/netutil.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h tcpip.h \
  libdnet-stripped/include/dnet.h scan_engine.h nmap_dns.h nmap_tty.h \
  utils.h nmap_error.h xml.h
tcpip.o: tcpip.cc nbase/nbase.h nbase/nbase_config.h nbase/getopt.h \
  nbase/nbase_ipv6.h portreasons.h nmap.h nmap_config.h nbase/nbase.h \
  global_structures.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h tcpip.h NmapOps.h output.h \
  portlist.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lua.h liblua/lualib.h nsock/include/nsock.h \
  nsock/include/nsock_config.h Target.h FingerPrintResults.h FPEngine.h \
  libnetutil/npacket.h libnetutil/ApplicationLayerElement.h \
  libnetutil/PacketElement.h libnetutil/netutil.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h scan_engine.h utils.h \
  nmap_error.h struct_ip.h
timing.o: timing.cc timing.h nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h NmapOps.h output.h portlist.h nse_main.h \
  liblua/lua.h liblua/luaconf.h liblua/lauxlib.h liblua/lua.h \
  liblua/lualib.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h utils.h nmap_error.h xml.h
traceroute.o: traceroute.cc nmap_dns.h nbase/nbase.h nbase/nbase_config.h \
  nbase/getopt.h nbase/nbase_ipv6.h nmap_error.h nmap_config.h \
  nbase/nbase.h nmap_tty.h osscan2.h nmap.h global_structures.h Target.h \
  FingerPrintResults.h FPEngine.h nsock/include/nsock.h \
  nsock/include/nsock_config.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lua.h liblua/lualib.h \
  portreasons.h portlist.h tcpip.h libdnet-stripped/include/dnet.h \
  scan_engine.h payload.h timing.h NmapOps.h output.h \
  nsock/include/nsock.h struct_ip.h
utils.o: utils.cc nmap.h nmap_config.h nbase/nbase.h nbase/nbase_config.h \
  nbase/getopt.h nbase/nbase_ipv6.h global_structures.h utils.h \
  nmap_error.h NmapOps.h output.h portlist.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lua.h liblua/lualib.h \
  portreasons.h nsock/include/nsock.h nsock/include/nsock_config.h
xml.o: xml.cc nmap.h nmap_config.h nbase/nbase.h nbase/nbase_config.h \
  nbase/getopt.h nbase/nbase_ipv6.h global_structures.h output.h \
  portlist.h nse_main.h liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lua.h liblua/lualib.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h xml.h
nse_main.o: nse_main.cc nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h nmap_error.h portlist.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lua.h liblua/lualib.h \
  portreasons.h nsock/include/nsock.h nsock/include/nsock_config.h \
  NmapOps.h output.h nsock/include/nsock.h timing.h Target.h \
  FingerPrintResults.h FPEngine.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h tcpip.h \
  libdnet-stripped/include/dnet.h scan_engine.h nmap_tty.h xml.h \
  nse_utility.h nse_fs.h nse_nsock.h nse_nmaplib.h nse_bit.h nse_binlib.h \
  nse_pcrelib.h nse_openssl.h nse_debug.h
nse_utility.o: nse_utility.cc Target.h nmap.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h FingerPrintResults.h FPEngine.h \
  nsock/include/nsock.h nsock/include/nsock_config.h libnetutil/npacket.h \
  libnetutil/ApplicationLayerElement.h libnetutil/PacketElement.h \
  libnetutil/netutil.h libdnet-stripped/include/dnet.h \
  libdnet-stripped/include/dnet/os.h libdnet-stripped/include/dnet/eth.h \
  libdnet-stripped/include/dnet/ip.h libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lua.h liblua/lualib.h \
  portreasons.h portlist.h tcpip.h libdnet-stripped/include/dnet.h \
  scan_engine.h nse_utility.h
nse_nsock.o: nse_nsock.cc nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap_error.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h NmapOps.h nmap.h \
  global_structures.h output.h portlist.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lua.h liblua/lualib.h \
  portreasons.h nsock/include/nsock.h utils.h tcpip.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h protocols.h libnetutil/netutil.h \
  nse_nsock.h nse_utility.h nse_ssl_cert.h
nse_dnet.o: nse_dnet.cc nsock/include/nsock.h \
  nsock/include/nsock_config.h nmap_error.h nmap_config.h nbase/nbase.h \
  nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h NmapOps.h nmap.h \
  global_structures.h output.h portlist.h nse_main.h liblua/lua.h \
  liblua/luaconf.h liblua/lauxlib.h liblua/lua.h liblua/lualib.h \
  portreasons.h nsock/include/nsock.h utils.h tcpip.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h protocols.h libnetutil/netutil.h \
  nse_utility.h struct_ip.h
nse_fs.o: nse_fs.cc liblua/lauxlib.h liblua/lua.h liblua/luaconf.h \
  liblua/lua.h nmap.h nmap_config.h nbase/nbase.h nbase/nbase_config.h \
  nbase/getopt.h nbase/nbase_ipv6.h global_structures.h nse_fs.h \
  nse_utility.h portlist.h nse_main.h liblua/lualib.h portreasons.h \
  nmap_error.h NmapOps.h output.h nsock/include/nsock.h \
  nsock/include/nsock_config.h
nse_nmaplib.o: nse_nmaplib.cc liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lua.h liblua/lualib.h nmap.h nmap_config.h \
  nbase/nbase.h nbase/nbase_config.h nbase/getopt.h nbase/nbase_ipv6.h \
  global_structures.h nmap_error.h NmapOps.h output.h portlist.h \
  nse_main.h portreasons.h nsock/include/nsock.h \
  nsock/include/nsock_config.h Target.h FingerPrintResults.h FPEngine.h \
  libnetutil/npacket.h libnetutil/ApplicationLayerElement.h \
  libnetutil/PacketElement.h libnetutil/netutil.h \
  libdnet-stripped/include/dnet.h libdnet-stripped/include/dnet/os.h \
  libdnet-stripped/include/dnet/eth.h libdnet-stripped/include/dnet/ip.h \
  libdnet-stripped/include/dnet/ip6.h \
  libdnet-stripped/include/dnet/addr.h \
  libdnet-stripped/include/dnet/arp.h \
  libdnet-stripped/include/dnet/icmp.h \
  libdnet-stripped/include/dnet/icmpv6.h \
  libdnet-stripped/include/dnet/tcp.h libdnet-stripped/include/dnet/udp.h \
  libdnet-stripped/include/dnet/sctp.h \
  libdnet-stripped/include/dnet/intf.h \
  libdnet-stripped/include/dnet/route.h \
  libdnet-stripped/include/dnet/fw.h libdnet-stripped/include/dnet/tun.h \
  libdnet-stripped/include/dnet/blob.h \
  libdnet-stripped/include/dnet/rand.h libnetutil/ARPHeader.h \
  libnetutil/NetworkLayerElement.h libnetutil/DataLinkLayerElement.h \
  libnetutil/EthernetHeader.h libnetutil/ICMPHeader.h \
  libnetutil/ICMPv4Header.h libnetutil/ICMPv6Header.h \
  libnetutil/ICMPv6Option.h libnetutil/ICMPv6RRBody.h \
  libnetutil/IPv4Header.h libnetutil/IPv6Header.h libnetutil/RawData.h \
  libnetutil/TCPHeader.h libnetutil/TransportLayerElement.h \
  libnetutil/UDPHeader.h libnetutil/HopByHopHeader.h \
  libnetutil/IPv6ExtensionHeader.h libnetutil/DestOptsHeader.h \
  libnetutil/FragmentHeader.h libnetutil/RoutingHeader.h \
  libnetutil/PacketParser.h libnetutil/netutil.h tcpip.h \
  libdnet-stripped/include/dnet.h scan_engine.h TargetGroup.h \
  service_scan.h libpcre/pcre.h nmap_dns.h osscan.h protocols.h \
  nse_nmaplib.h nse_utility.h nse_nsock.h nse_dnet.h
nse_debug.o: nse_debug.cc liblua/lua.h liblua/luaconf.h liblua/lauxlib.h \
  liblua/lua.h nmap.h nmap_config.h nbase/nbase.h nbase/nbase_config.h \
  nbase/getopt.h nbase/nbase_ipv6.h global_structures.h nse_debug.h \
  output.h portlist.h nse_main.h liblua/lualib.h portreasons.h \
  nsock/include/nsock.h nsock/include/nsock_config.h
nse_pcrelib.o: nse_pcrelib.cc liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lua.h nbase/nbase.h nbase/nbase_config.h \
  nbase/getopt.h nbase/nbase_ipv6.h nmap_error.h nmap_config.h \
  nbase/nbase.h libpcre/pcre.h nse_pcrelib.h
nse_binlib.o: nse_binlib.cc nbase/nbase.h nbase/nbase_config.h \
  nbase/getopt.h nbase/nbase_ipv6.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lua.h nse_binlib.h
nse_bit.o: nse_bit.cc liblua/lauxlib.h liblua/lua.h liblua/luaconf.h \
  liblua/lua.h nse_bit.h
nse_openssl.o: nse_openssl.cc liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lua.h nse_openssl.h
nse_ssl_cert.o: nse_ssl_cert.cc nbase/nbase.h nbase/nbase_config.h \
  nbase/getopt.h nbase/nbase_ipv6.h liblua/lua.h liblua/luaconf.h \
  liblua/lauxlib.h liblua/lua.h nse_nsock.h nse_main.h liblua/lualib.h \
  nmap.h nmap_config.h nbase/nbase.h global_structures.h
